In [5]:
import numpy as np
import pandas as pd

## Datatypes and Attributes

In [6]:
# numpy's main datatype is ndarray
arr1d = np.array([1,2,3,4,5])
arr1d

array([1, 2, 3, 4, 5])

In [7]:
arr2d = np.array([[1,2,3,74,5],
                  [11,2,53,4,5],
                  [13,12,3,4,5],
                  [31,21,3,4,5]])
arr2d

array([[ 1,  2,  3, 74,  5],
       [11,  2, 53,  4,  5],
       [13, 12,  3,  4,  5],
       [31, 21,  3,  4,  5]])

In [48]:
arr3d = np.array([[[1,2,3,74,5],
                   [13,12,3,4,5],
                   [31,21,3,4,5]],
                  [[1,2,3,74,5],
                   [13,12,3,4,5],
                   [31,21,3,4,5]]])
arr3d

array([[[ 1,  2,  3, 74,  5],
        [13, 12,  3,  4,  5],
        [31, 21,  3,  4,  5]],

       [[ 1,  2,  3, 74,  5],
        [13, 12,  3,  4,  5],
        [31, 21,  3,  4,  5]]])

In [43]:
arr1d.shape

(5,)

In [44]:
arr2d.shape

(4, 5)

In [45]:
arr3d.shape

(2, 3, 5)

In [46]:
arr1d.ndim, arr2d.ndim, arr3d.ndim

(1, 2, 3)

In [47]:
arr1d.dtype, arr2d.dtype, arr3d.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [48]:
arr1d.size, arr2d.size, arr3d.size

(5, 20, 30)

In [49]:
type(arr1d), type(arr2d), type(arr3d)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### numpy array as dataframe of pandas

In [50]:
import pandas as pd

In [51]:
df = pd.DataFrame(arr2d)          #wont work on 3d array

In [52]:
df

0   1   2   3  4
0   1   2   3  74  5
1  11   2  53   4  5
2  13  12   3   4  5
3  31  21   3   4  5

## Creating numpy arrays

In [53]:
arr = np.ones((4,4), dtype = int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [54]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
arr = np.twos((4,4), dtype = int)
arr

AttributeError: module 'numpy' has no attribute 'twos'

## random

In [61]:
arr = np.random.randint(0, 10, size = (3,6))
arr

array([[9, 5, 6, 4, 3, 2],
       [0, 2, 5, 2, 5, 0],
       [9, 2, 7, 3, 6, 2]], dtype=int32)

In [65]:
arr.shape, arr.size, arr.ndim, type(arr)

((3, 6), 18, 2, numpy.ndarray)

In [20]:
arr = np.random.random(size = (3,5))
arr
#the random values change everytime we run the code, to overcome this.......

array([[0.59021848, 0.58521502, 0.49126025, 0.70073933, 0.86472762],
       [0.92150426, 0.84111214, 0.50721949, 0.80885187, 0.22156516],
       [0.55118264, 0.02765254, 0.16286302, 0.0730452 , 0.00894068]])

In [43]:
#use seed() to make the values same everytime we run
np.random.seed(1)
arr = np.random.randint(2, 15, size = (3,5))
arr

array([[ 7, 13, 14, 10, 11],
       [13,  7,  2,  2,  3],
       [14,  9, 14,  8, 11]], dtype=int32)

In [37]:
np.random.seed(2)
arrr = np.random.randint(2, 15, size = (3,5))
arrr

array([[10, 10,  8, 13,  4],
       [13, 10,  9,  4,  3],
       [13,  7, 12,  6, 14]], dtype=int32)

## viewing arrays and matrices

In [44]:
np.unique(arr)       #unique elements of arr

array([ 2,  3,  7,  8,  9, 10, 11, 13, 14], dtype=int32)

In [49]:
arr1d

array([1, 2, 3, 4, 5])

In [50]:
arr1d[0]

np.int64(1)

In [51]:
arr2d[0]

array([ 1,  2,  3, 74,  5])

In [52]:
arr3d[0]

array([[ 1,  2,  3, 74,  5],
       [13, 12,  3,  4,  5],
       [31, 21,  3,  4,  5]])

In [53]:
arr3d.shape

(2, 3, 5)

In [54]:
arr3d

array([[[ 1,  2,  3, 74,  5],
        [13, 12,  3,  4,  5],
        [31, 21,  3,  4,  5]],

       [[ 1,  2,  3, 74,  5],
        [13, 12,  3,  4,  5],
        [31, 21,  3,  4,  5]]])

![](numpyArray.png)

In [60]:
arr3d[:2, :2, :4]

array([[[ 1,  2,  3, 74],
        [13, 12,  3,  4]],

       [[ 1,  2,  3, 74],
        [13, 12,  3,  4]]])

In [85]:
np.random.seed(0)
arr4d = np.random.randint(5, 15, (2,3,2,4))
arr4d

array([[[[10,  5,  8,  8],
         [12, 14,  8, 10]],

        [[ 7,  9, 12, 11],
         [13, 13,  6, 11]],

        [[12, 12, 13,  6],
         [10, 14, 13, 14]]],


       [[[ 9,  8,  5,  8],
         [10,  5,  7,  8]],

        [[13,  6,  8,  8],
         [ 8, 12,  5,  6]],

        [[14, 14,  5,  9],
         [12,  8,  7, 12]]]], dtype=int32)

In [93]:
arr4d[:, :, :, :2]

array([[[[10,  5],
         [12, 14]],

        [[ 7,  9],
         [13, 13]],

        [[12, 12],
         [10, 14]]],


       [[[ 9,  8],
         [10,  5]],

        [[13,  6],
         [ 8, 12]],

        [[14, 14],
         [12,  8]]]], dtype=int32)

## Manipulating and comparing arrays

### arithmetic

In [96]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],
               [4,5,6]])

In [97]:
a1+a2

array([[2, 4, 6],
       [5, 7, 9]])

In [99]:
a1-a2

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [100]:
a2-a1

array([[0, 0, 0],
       [3, 3, 3]])

In [104]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [105]:
a2*a1

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [110]:
a2/a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [108]:
a1/a2

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [111]:
a2//a1

array([[1, 1, 1],
       [4, 2, 2]])

In [113]:
a = np.array([4,5])

In [114]:
a*a2

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

In [115]:
a/a2

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

In [116]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [117]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [120]:
np.add(a1,a2)

array([[2, 4, 6],
       [5, 7, 9]])

In [121]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [122]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

### aggregation
Aggregation - bringing things together, doing a similar thing on a number of things.

In [123]:
sum(a1)

np.int64(6)

In [125]:
np.sum(a1)

np.int64(6)

Tip: Use NumPy's np.sum() on NumPy arrays and Python's sum() on Python lists.

In [131]:
big_array = np.random.random(10000)

In [136]:
%timeit sum(big_array)          #python's sum()
%timeit np.sum(big_array)       #numpy's sum()

2.66 ms ± 36.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
28.5 μs ± 2.3 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [152]:
np.random.seed(5)
temp = np.random.randint(0, 50, 50)
temp

array([35, 14, 47, 38, 16,  9,  8, 36, 39, 27, 48, 30, 16,  7, 12, 15, 49,
       39, 16, 27, 44, 13, 11,  1, 47, 30, 20, 22, 18,  9, 42, 41, 41,  1,
       18, 39, 16, 14,  5,  0, 16,  4, 46, 36, 41, 27, 31,  2,  4, 38],
      dtype=int32)

In [153]:
np.max(temp), np.min(temp), np.mean(temp)

(np.int32(49), np.int32(0), np.float64(24.1))

### Standard Deviation and mean

In [157]:
np.var(temp)

np.float64(227.16999999999996)

**Variance** : measure of the avg degree to which each number differs to the mean <br>
The variance is the averaged squared differences of the mean.

To work it out, you:
1. Work out the mean
2. For each number, subtract the mean and square the result
3. Find the average of the squared differences

In [158]:
np.std(temp)

np.float64(15.07215976560758)

**Standard deviation** is a measure of how spread out numbers are from the mean.<br>
SD is root of variance.

In [160]:
np.sqrt(np.var(temp))

np.float64(15.07215976560758)

In [166]:
# example
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [164]:
np.var(high_var_array), np.var(low_var_array)

(np.float64(4296133.472222221), np.float64(8.0))

In [167]:
np.std(high_var_array), np.std(low_var_array)

(np.float64(2072.711623024829), np.float64(2.8284271247461903))

## Reshape and tranpose

In [4]:
np.random.seed(0)
a3 = np.random.randint(2, 10, size = (2,3,2))
a2 = np.random.randint(2, 10, size = (2,3))

In [5]:
a3*a2

ValueError: operands could not be broadcast together with shapes (2,3,2) (2,3) 

In [6]:
a3

array([[[6, 9],
        [7, 2],
        [5, 5]],

       [[5, 9],
        [3, 5],
        [7, 4]]], dtype=int32)

In [7]:
a2

array([[6, 9, 8],
       [2, 2, 6]], dtype=int32)

In [8]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[6],
        [9],
        [8]],

       [[2],
        [2],
        [6]]], dtype=int32)

In [9]:
a3*a2_reshape

array([[[36, 54],
        [63, 18],
        [40, 40]],

       [[10, 18],
        [ 6, 10],
        [42, 24]]], dtype=int32)

In [12]:
a2_reshape.reshape(2,2,1)

ValueError: cannot reshape array of size 6 into shape (2,2,1)

In [15]:
a2_reshape = a2_reshape.reshape(2,3)
a2

array([[6, 9, 8],
       [2, 2, 6]], dtype=int32)

In [16]:
a2.shape

(2, 3)

In [17]:
# transpose
a2.T

array([[6, 2],
       [9, 2],
       [8, 6]], dtype=int32)

In [18]:
a2.T.shape

(3, 2)

## Dot product

In [42]:
np.random.seed(0)
mat1 = np.random.randint(1, 10, size = (2,5))
mat2 = np.random.randint(1, 10, size = (2,5))

In [43]:
mat1

array([[6, 1, 4, 4, 8],
       [4, 6, 3, 5, 8]], dtype=int32)

In [44]:
mat2

array([[7, 9, 9, 2, 7],
       [8, 8, 9, 2, 6]], dtype=int32)

In [45]:
mat1 * mat2

array([[42,  9, 36,  8, 56],
       [32, 48, 27, 10, 48]], dtype=int32)

In [46]:
np.dot(mat1,mat2)

ValueError: shapes (2,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)

In [47]:
mat2.reshape(5,2)

array([[7, 9],
       [9, 2],
       [7, 8],
       [8, 9],
       [2, 6]], dtype=int32)

In [48]:
mat2.T

array([[7, 8],
       [9, 8],
       [9, 9],
       [2, 2],
       [7, 6]], dtype=int32)

In [50]:
np.dot(mat1, mat2.T)

array([[151, 148],
       [175, 165]], dtype=int32)

### Dot product eg, nut butter sales

In [46]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(7, 3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7],
       [14, 17,  5],
       [13,  8,  9]], dtype=int32)

In [47]:
weekly_sales = pd.DataFrame(sales_amount,
                     columns = ["Almond", "Peanut", "Cashew"],
                     index = ["Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"])
weekly_sales

Almond  Peanut  Cashew
Mon        12      15       0
Tues        3       3       7
Wed         9      19      18
Thurs       4       6      12
Fri         1       6       7
Sat        14      17       5
Sun        13       8       9

In [48]:
price_amount = np.array([10, 8, 12])
price_amount.shape

(3,)

In [49]:
price = pd.DataFrame(price_amount.reshape(1,3), 
                     index = ["Price"],
                     columns = ["Almond", "Peanut", "Cashew"])
price

Almond  Peanut  Cashew
Price      10       8      12

In [52]:
total = np.dot(sales_amounts, price_amount)
total

array([240, 138, 458, 232, 142, 336, 302])

In [66]:
weekly_sales["Total"] = total
weekly_sales

Almond  Peanut  Cashew  Total
Mon        12      15       0    240
Tues        3       3       7    138
Wed         9      19      18    458
Thurs       4       6      12    232
Fri         1       6       7    142
Sat        14      17       5    336
Sun        13       8       9    302

## comparison operators

In [8]:
arr1d

array([1, 2, 3, 4, 5])

In [9]:
arr2d

array([[ 1,  2,  3, 74,  5],
       [11,  2, 53,  4,  5],
       [13, 12,  3,  4,  5],
       [31, 21,  3,  4,  5]])

In [10]:
arr1d > arr2d

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [11]:
arr1d >= arr2d

array([[ True,  True,  True, False,  True],
       [False,  True, False,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True]])

In [12]:
arr2d > arr1d

array([[False, False, False,  True, False],
       [ True, False,  True, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False]])

In [14]:
bool_array = arr2d >= arr1d
bool_array

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [15]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

## Sorting Arrays

In [16]:
arr1d, arr2d

(array([1, 2, 3, 4, 5]),
 array([[ 1,  2,  3, 74,  5],
        [11,  2, 53,  4,  5],
        [13, 12,  3,  4,  5],
        [31, 21,  3,  4,  5]]))

In [21]:
np.sort(arr2d)

array([[ 1,  2,  3,  5, 74],
       [ 2,  4,  5, 11, 53],
       [ 3,  4,  5, 12, 13],
       [ 3,  4,  5, 21, 31]])

In [24]:
new = np.random.randint(2,8, (3,6))
new

array([[6, 3, 5, 2, 7, 7],
       [2, 2, 6, 7, 6, 2],
       [2, 3, 4, 7, 2, 3]], dtype=int32)

In [25]:
np.argsort(new)

array([[3, 1, 2, 0, 4, 5],
       [0, 1, 5, 2, 4, 3],
       [0, 4, 1, 5, 2, 3]])

In [28]:
new

array([[6, 3, 5, 2, 7, 7],
       [2, 2, 6, 7, 6, 2],
       [2, 3, 4, 7, 2, 3]], dtype=int32)

In [29]:
np.argmin(new), np.argmax(new)

(np.int64(3), np.int64(4))

Its wrong, because

When you call:
np.argmin(new)
It flattens the array into a 1D array (row-major order, aka C-style), and returns the index of the minimum value in this 1D version.

[6, 3, 5, 2, 7, 7, 2, 2, 6, 7, 6, 2, 2, 3, 4, 7, 2, 3]

np.argmin(new) returns index 3 — value 2
np.argmax(new) returns index 4 — value 7

In [30]:
np.argmin(arr1d), np.argmax(arr2d)

(np.int64(0), np.int64(4))

In [32]:
np.argmin(new, axis = 0), np.argmin(new, axis = 1)

(array([1, 1, 2, 0, 2, 1]), array([3, 0, 0]))

In [33]:
np.argmax(new, axis = 0), np.argmax(new, axis = 1)

(array([0, 0, 1, 1, 0, 0]), array([4, 3, 3]))

## numpy practical example - image to array

In [1]:
# turn image into numpy array
from matplotlib.image import imread

In [8]:
panda = imread("numpy-images/panda.png")
dog = imread("numpy-images/dog-photo.png")
car = imread("numpy-images/car-photo.png")

In [11]:
panda.shape

(2330, 3500, 3)

In [16]:
panda[:7, :7, :3]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667]],

       [[0.05490196, 0.10588