# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [127]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [128]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[10, 20, 30],
               [40, 50, 60]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[10, 20, 30],
                [40, 50, 60]],
               [[ 4, 5, 6],
                [ 7, 8, 9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.size, type(a1)

(1, dtype('int64'), 3, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
a2.ndim, a2.dtype, a2.size, type(a2)

(2, dtype('int64'), 6, numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
a3.ndim, a3.dtype, a3.size, type(a3)

(3, dtype('int64'), 12, numpy.ndarray)

In [10]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0   1   2
0  10  20  30
1  40  50  60

In [11]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7,2,3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr = np.random.randint(0, 10, (7,2))
arr

array([[3, 3],
       [8, 3],
       [3, 4],
       [7, 6],
       [4, 8],
       [8, 0],
       [3, 5]], dtype=int32)

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
float_array = np.random.rand(3,5)
float_array

array([[0.50376361, 0.91078795, 0.83159925, 0.99746768, 0.37997318],
       [0.56490685, 0.43485651, 0.19087391, 0.30729207, 0.98388139],
       [0.32828246, 0.4314222 , 0.5298587 , 0.38646834, 0.53431095]])

In [39]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
nums = np.random.randint(0, 10, (4,6))
nums

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [40]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
nums = np.random.randint(0, 10, (3,7))

# Find the unique numbers in the array you just created
np.unique(nums)

array([0, 1, 2, 3, 4, 6, 8, 9], dtype=int32)

In [41]:
# Find the 0'th index of the latest array you created
nums[0]

array([8, 0, 9, 2, 6, 3, 8], dtype=int32)

In [42]:
# Get the first 2 rows of latest array you created
nums[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]], dtype=int32)

In [43]:
# Get the first 2 values of the first 2 rows of the latest array
nums[:2, :2]

array([[8, 0],
       [2, 4]], dtype=int32)

In [60]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(0)
num1 = np.random.randint(0, 10, (3,5))
num2 = np.random.randint(0, 10, (3,5))

In [61]:
num1

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]], dtype=int32)

In [62]:
num2

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]], dtype=int32)

In [63]:
# Add the two arrays together
num1 + num2

array([[11,  7, 10, 11,  8],
       [14, 12, 13, 11,  8],
       [10,  6, 11, 13,  1]], dtype=int32)

In [64]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5,3))

In [65]:
# Try add the array of ones and the other most recent array together
ones + num2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [66]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3,5))

In [67]:
# Subtract the new array of ones from the other most recent array
num2 - ones

array([[ 5.,  6.,  6.,  7.,  0.],
       [ 4.,  8.,  7.,  8.,  3.],
       [ 2., -1.,  2.,  4., -1.]])

In [68]:
# Multiply the ones array with the latest array
ones * num2

array([[6., 7., 7., 8., 1.],
       [5., 9., 8., 9., 4.],
       [3., 0., 3., 5., 0.]])

In [69]:
# Take the latest array to the power of 2 using '**'
num2**2

array([[36, 49, 49, 64,  1],
       [25, 81, 64, 81, 16],
       [ 9,  0,  9, 25,  0]], dtype=int32)

In [70]:
# Do the same thing with np.square()
np.square(num2)

array([[36, 49, 49, 64,  1],
       [25, 81, 64, 81, 16],
       [ 9,  0,  9, 25,  0]], dtype=int32)

In [71]:
# Find the mean of the latest array using np.mean()
np.mean(num2)

np.float64(5.0)

In [72]:
# Find the maximum of the latest array using np.max()
np.max(num2)

np.int32(9)

In [73]:
# Find the minimum of the latest array using np.min()
np.min(num2)

np.int32(0)

In [74]:
# Find the standard deviation of the latest array
np.std(num2)

np.float64(2.988868236194653)

In [75]:
# Find the variance of the latest array
np.var(num2)

np.float64(8.933333333333334)

In [76]:
# Reshape the latest array to (3, 5, 1)
num2.reshape(3,5,1)

array([[[6],
        [7],
        [7],
        [8],
        [1]],

       [[5],
        [9],
        [8],
        [9],
        [4]],

       [[3],
        [0],
        [3],
        [5],
        [0]]], dtype=int32)

In [77]:
# Transpose the latest array
num2.T

array([[6, 5, 3],
       [7, 9, 0],
       [7, 8, 3],
       [8, 9, 5],
       [1, 4, 0]], dtype=int32)

What does the transpose do?

In [78]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(0)
n1 = np.random.randint(0, 10, (3,3))
n2 = np.random.randint(0, 10, (3,2))

In [81]:
# Perform a dot product on the two newest arrays you created
n1.dot(n2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]], dtype=int32)

In [93]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(0)
n1 = np.random.randint(0, 10, (4,3))
n2 = np.random.randint(0, 10, (4,3))

In [94]:
# Perform a dot product on the two newest arrays you created
n1.dot(n2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [95]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
n1.dot(n2.T)

array([[ 43,  51,  55,  72],
       [ 89, 130,  76, 164],
       [ 66,  67,  39,  85],
       [ 94, 115,  69, 146]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [96]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [97]:
# Compare the two arrays with '>'
n1>n2

array([[False, False,  True],
       [False, False,  True],
       [False,  True, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [98]:
# Compare the two arrays with '>='
n1 >= n2

array([[False, False,  True],
       [False,  True,  True],
       [False,  True, False],
       [False, False, False]])

In [99]:
# Find which elements of the first array are greater than 7
n1 > 7

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [88]:
# Which parts of each array are equal? (try using '==')
n1 == 7

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False,  True, False]])

In [102]:
# Sort one of the arrays you just created in ascending order
np.sort(n1)

array([[0, 3, 5],
       [3, 7, 9],
       [2, 3, 5],
       [4, 6, 7]], dtype=int32)

In [108]:
# Sort the indexes of one of the arrays you just created
np.argsort(n1)

array([[1, 2, 0],
       [0, 1, 2],
       [2, 0, 1],
       [0, 2, 1]])

In [115]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(n1), n1

(np.int64(5),
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32))

In [116]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(n1)

np.int64(1)

In [117]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.max(n1, axis = 1)

array([5, 9, 5, 7], dtype=int32)

In [118]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.max(n1, axis = 0)

array([5, 7, 9], dtype=int32)

In [119]:
# Create an array of normally distributed random numbers
arr = np.random.randn(3, 3)
arr

array([[-1.27814912,  1.43737068, -0.07770457],
       [ 1.08963016,  0.09654267,  1.41866711],
       [ 1.16827314,  0.94718595,  1.08548703]])

In [126]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr = np.linspace(1, 100, 10)
arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.